name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install Dep
        run: |
          pip install nbconvert
      - name: build
        run: |
          jupyter nbconvert --to html --output-dir output *.ipynb
      - name: Ls
        run: ls output
      - name: Write Index
        run: python ./write_index.py