name: build

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install Dep
        run: |
          pip install nbconvert
          sudo apt install pandoc
          sudo apt install texlive-xetex texlive-fonts-recommended texlive-plain-generic